DROP TABLE IF EXISTS TAG_AD;
DROP TABLE IF EXISTS AD;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS TAG;

PRAGMA foreign_keys = ON;

CREATE TABLE TAG(
    ID INTEGER PRIMARY KEY,
    TITLE TEXT NOT NULL
);

CREATE TABLE CATEGORY(
    ID INTEGER PRIMARY KEY,
    TITLE TEXT NOT NULL);

CREATE TABLE ad (
    ID INTEGER PRIMARY KEY,
    TITLE TEXT,
    DESCRIPTION TEXT,
    OWNER TEXT,
    PRICE INTEGER,
    CREATEDAT DATE,
    PICTURE TEXT,
    LOCATION TEXT,
    CATEGORYID INTEGER NOT NULL,
    FOREIGN KEY(CATEGORYID) REFERENCES CATEGORY(ID));

CREATE TABLE TAG_AD (
    ID INTEGER PRIMARY KEY,
    TAGID INTEGER NOT NULL,
    ADID INTEGER NOT NULL,
    FOREIGN KEY(TAGID) REFERENCES TAG(ID),
    FOREIGN KEY(ADID) REFERENCES ad(ID)
);

INSERT INTO CATEGORY (TITLE) VALUES ('AUTRE');
INSERT INTO TAG (TITLE) VALUES ('NEUF'), ('SOLDE');


INSERT INTO ad ( TITLE, DESCRIPTION,OWNER,PRICE,CREATEDAT,PICTURE,LOCATION, CATEGORYID) VALUES
    ('Vélo à vendre', 'Vélo en bon état, peu servi', 'john.doe@gmail.com', 150, '2024-03-19', NULL, 'Paris', 1);

INSERT INTO TAG_AD (TAGID, ADID) VALUES(1,1);
INSERT INTO TAG_AD (TAGID, ADID) VALUES(2,1);


SELECT * FROM AD JOIN CATEGORY ON AD.ID = CATEGORY.ID;